/* PROGRAMS */
export const PROGRAMS_LOAD = 'PROGRAMS_LOAD';
export const PROGRAMS_LOAD_ERROR = 'PROGRAMS_LOAD_ERROR';
export const PROGRAMS_SET = 'PROGRAMS_SET';
export const PROGRAM_STAGES_LOAD = 'PROGRAM_STAGES_LOAD';
export const PROGRAM_STAGES_LOAD_ERROR = 'PROGRAM_STAGES_LOAD_ERROR';
export const PROGRAM_STAGES_SET = 'PROGRAM_STAGES_SET';
export const PROGRAM_ATTRIBUTES_LOAD = 'PROGRAM_ATTRIBUTES_LOAD';
export const PROGRAM_ATTRIBUTES_LOAD_ERROR = 'PROGRAM_ATTRIBUTES_LOAD_ERROR';
export const PROGRAM_ATTRIBUTES_SET = 'PROGRAM_ATTRIBUTES_SET';
export const PROGRAM_DATA_ELEMENTS_LOAD = 'PROGRAM_DATA_ELEMENTS_LOAD';
export const PROGRAM_DATA_ELEMENTS_LOAD_ERROR = 'PROGRAM_DATA_ELEMENTS_LOAD_ERROR';
export const PROGRAM_DATA_ELEMENTS_SET = 'PROGRAM_DATA_ELEMENTS_SET';
export const PROGRAM_INDICATORS_LOAD = 'PROGRAM_INDICATORS_LOAD';
export const PROGRAM_INDICATORS_LOAD_ERROR = 'PROGRAM_INDICATORS_LOAD_ERROR';
export const PROGRAM_INDICATORS_SET = 'PROGRAM_INDICATORS_SET ';
export const PROGRAM_STAGE_DATA_ELEMENTS_LOAD = 'PROGRAM_STAGE_DATA_ELEMENTS_LOAD';
export const PROGRAM_STAGE_DATA_ELEMENTS_LOAD_ERROR = 'PROGRAM_STAGE_DATA_ELEMENTS_LOAD_ERROR';
export const PROGRAM_STAGE_DATA_ELEMENTS_SET = 'PROGRAM_STAGE_DATA_ELEMENTS_SET';

/* OPTION SETS */
export const OPTION_SET_LOAD = 'OPTION_SET_LOAD';
export const OPTION_SET_LOAD_ERROR = 'OPTION_SET_LOAD_ERROR';
export const OPTION_SET_ADD = 'OPTION_SET_ADD';

/* LOADING */
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';

/* FORM */
export const FORM_SET = 'FORM_SET';
export const TOGGLE_FORM_ORGUNIT = 'TOGGLE_FORM_ORGUNIT';
export const FORM_PERIOD_SET = 'FORM_PERIOD_SET';
export const FORM_START_DATE_SET = 'FORM_START_DATE_SET';
export const FORM_END_DATE_SET = 'FORM_END_DATE_SET';
export const FORM_PERIOD_TYPE_SET = 'FORM_PERIOD_TYPE_SET';

/* ORGANISATION UNITS */
export const ORGANISATION_UNIT_LOAD = 'ORGANISATION_UNIT_LOAD';
export const ORGANISATION_UNIT_SET = 'ORGANISATION_UNIT_SET';
export const ORGANISATION_UNIT_CLOSE = 'ORGANISATION_UNIT_CLOSE';
export const ORGANISATION_UNIT_SELECT = 'ORGANISATION_UNIT_SELECT';
export const ORGANISATION_UNIT_UNSELECT = 'ORGANISATION_UNIT_UNSELECT';
export const ORGANISATION_UNIT_RELOCATE_START = 'ORGANISATION_UNIT_RELOCATE_START';
export const ORGANISATION_UNIT_RELOCATE_STOP = 'ORGANISATION_UNIT_RELOCATE_STOP';
export const ORGANISATION_UNIT_COORDINATE_CHANGE = 'ORGANISATION_UNIT_COORDINATE_CHANGE';
export const ORGANISATION_UNIT_COORDINATE_CHANGE_ERROR =
    'ORGANISATION_UNIT_COORDINATE_CHANGE_ERROR';
export const ORGANISATION_UNIT_COORDINATE_SET = 'ORGANISATION_UNIT_COORDINATE_SET';
export const ORGANISATION_UNIT_TREE_LOAD = 'ORGANISATION_UNIT_TREE_LOAD';
export const ORGANISATION_UNIT_TREE_LOAD_ERROR = 'ORGANISATION_UNIT_TREE_LOAD_ERROR';
export const ORGANISATION_UNIT_TREE_SET = 'ORGANISATION_UNIT_TREE_SET';
export const ORGANISATION_UNIT_GROUPS_LOAD = 'ORGANISATION_UNIT_GROUPS_LOAD';
export const ORGANISATION_UNIT_GROUPS_LOAD_ERROR = 'ORGANISATION_UNIT_GROUPS_LOAD_ERROR';
export const ORGANISATION_UNIT_GROUPS_SET = 'ORGANISATION_UNIT_GROUPS_SET';
export const ORGANISATION_UNIT_GROUP_SETS_LOAD = 'ORGANISATION_UNIT_GROUP_SETS_LOAD';
export const ORGANISATION_UNIT_GROUP_SETS_LOAD_ERROR = 'ORGANISATION_UNIT_GROUP_SETS_LOAD_ERROR';
export const ORGANISATION_UNIT_GROUP_SETS_SET = 'ORGANISATION_UNIT_GROUP_SETS_SET';
export const ORGANISATION_UNIT_LEVELS_SET = 'ORGANISATION_UNIT_LEVELS_SET';
export const ORGANISATION_UNIT_LEVELS_LOAD = 'ORGANISATION_UNIT_LEVELS_LOAD';
export const ORGANISATION_UNIT_LEVELS_LOAD_ERROR = 'ORGANISATION_UNIT_LEVELS_LOAD_ERROR';

/* REPORT */
export const REPORT_LOAD = 'REPORT_LOAD';
export const REPORT_LOAD_SUCCESS = 'REPORT_LOAD_SUCCESS';
export const REPORT_LOAD_ERROR = 'REPORT_LOAD_ERROR';
export const REPORT_SAVE = 'REPORT_SAVE';
export const REPORT_SAVE_NEW = 'REPORT_SAVE_NEW';
export const REPORT_SAVE_NEW_SUCCESS = 'REPORT_SAVE_NEW_SUCCESS';
export const REPORT_SAVE_NEW_ERROR = 'REPORT_SAVE_NEW_ERROR';

/* USER */
export const USER_SETTINGS_SET = 'USER_SETTINGS_SET';
